### PR TITLE
CI pipeline

### PR DESCRIPTION
**Pull request by Armagetron**
This pull request adds a travis pipeline to automatically test any changes. Parts of this code have been contributed by @m273d15. It creates an environment and launches the docker containers and runs our test cases.

It depends on the PR #23, #24 and #25 . Please merge it only after these have been merged into master.

### CODE REVIEW

**Comment by nils-wisiol** [comment]
after rebase, this should be ready to merge!

**Comment by Armagetron** [comment]
@nils-wisiol done!

**Review by nils-wisiol — CHANGES_REQUESTED** [review]
Please squash commits whenever they change something that was introduced in this PR, e.g. in 9dba0b0d2087f2a7efb91af671aa5a4664830f09.

I can see that converting the line breaks in all those very fine grained commits is a pain, so I propose to introduce the entire file with just one commit rather than breaking it up in it's parts.

**Comment by Armagetron** [comment]
@nils-wisiol done!

**Comment by nils-wisiol** [comment]
Please update the commit message. The current text is somewhat misleading, especially for fix-up commits that are no longer 'visible' in history (e.g. change EOL).

[Hints on how to phrase good commit messages](https://chris.beams.io/posts/git-commit/).

**Comment by Armagetron** [comment]
done

**Comment by nils-wisiol** [comment]
this is [green even if tests fail](https://travis-ci.org/swp-fu-eid/eid-fu-swp/builds/264642116#L1697). The command inspecting the exit code [fails](https://travis-ci.org/swp-fu-eid/eid-fu-swp/builds/264642116#L1720).

**Comment by Armagetron** [comment]
It should work now.

**Comment by nils-wisiol** [comment]
lgtm

**Pull request merged**
