### PR TITLE
Windows fix

### PR DESCRIPTION
**Pull request by BenjaminKeller**
_**Disclaimer:**_ This is a duplicate of #2. As the old pull request was merging into develop and was missing one bugfix, I opened a new one. It has to be approved by the responsibles, too.

## Description
This branch contains fixes for running the example on Windows. See #1 for more information. All members which are forced to use Windows should review this.

## Naming of compose files
_**This is the only comment from #2. Therefore I copied it.**_
At now there exist two docker compose files `docker-compose.yml` and `docker-compose.logging.yml`. Looking at the file names the intention is not clear. I think we have to improve on that.

### 1. Solution: Renaming
`docker-compose.yml` -> `docker-compose.syslogd.yml`
`docker-compose.logging` -> `docker-compose.default.yml`

### 2. Solution: Switch to default logging
Is there any reason we want to log with syslogd? I am not a docker specialist.

### 3. Solution: Remain
If there is a good reason for logging with syslogd we should appreciate that and get to used by it.

### Result
I think the first solution is the best as it forces you to choose one and rename it.

### CODE REVIEW

**Review by nils-wisiol — CHANGES_REQUESTED** [review]
@BenjaminKeller, before this PR there are two `docker-compose.yml`, one for "production" use, the other for testing (`docker-compose.test.yml`). `master` doesn't have any `docker-compose.logging`.

I'd suggest using the inheritance features of docker-compose to apply or no apply logging to syslog. Easiest way to do so is to move the logging stanzas to a seperate file, e.g. `docker-compose.syslog.yml` (similarly done with the `docker-compose.test.yml`). This will reduce config duplication and avoid future errors. Alternatively, remove logging to syslog altogether.

Please squash fix up commits like 8a013c1 into their original commits to keep `master`'s commit history clean whenever possible. Bugfix commits should only be used if bugs already made it to `master`. (Same for cc6c565fb2146d79642e816b0b906b928b63e539)

Also, please configure travis to be used with this repository.

**Comment by Armagetron** [comment]
@nils-wisiol Travis will be used as soon as this PR and #29 are both merged into master. Or do you want both PR merged before they are submitted into master?

**Comment by BenjaminKeller** [comment]
@nils-wisiol I cleaned the commits as instructed and moved the syslogd configuration to an additional file. The syslogd config can now be run by using:
```
docker-compose -f docker-compose.yml -f docker-compose.syslogd.yml up --build
```

**Comment by nils-wisiol** [comment]
@Armagetron I may be overlooking something, but wouldn't it be worth running this PR through the existing travis configuration? This PR modifies the www configuration, that's why the tests could be useful.

Other than that, this lgtm

**Comment by Armagetron** [comment]
@nils-wisiol Should we merge the travis config into this branch?

**Comment by nils-wisiol** [comment]
My bad - I somehow thought there was already a configuration in `master` that was just not active. Let's add the CI later then.

**Pull request merged**
