### PR TITLE
Add eid server wsdl to project

### PR DESCRIPTION
**Pull request by Armagetron**
I added the WSDL of the eID Server from the TR-03130 to the project for further work.

### CODE REVIEW

**Comment by nils-wisiol** [comment]
How are those file licensed? Is there any way those can be included in the project without keeping a copy of them in this repository? Is the BSI the source of those files? (Keeping external resources external comes at the cost of a possible unavailability when, say, the upstream source is shut down. This can be considered unlikely for the BSI. It provides the benefit of have a clearer versioning and easier updates.)

**Comment by Armagetron** [comment]
I already had the problem, that some of the external resources where down or have been moved.

Furthermore, the file provided by the BSI is no valid WSDL. I had to update it. I do not see easier updates since we need to update our code if the standard changes.

I just wanted to have those files in the repository so that it is clear what my code will be based on. I can work without these files in the repository but that will make it harder to validate the code.

**Comment by nils-wisiol** [comment]
Good point. I think keeping the files solely for documentation purpose in our repository is a good idea. Please add the source and some information on why you changed the files to the commit messages, then this lgtm

(Also, for git commit messages, please have a brief look on [some ideas to write and format](https://chris.beams.io/posts/git-commit/) them.)

**Comment by Armagetron** [comment]
I added a README with links to all sources.

**Comment by nils-wisiol** [comment]
Looks good. I'd like to ask @zervnet before merging. This will result in delay until Friday, is that okay for you?

**Comment by Armagetron** [comment]
I am currently working on the eID-Server. All automatic code generators are rather old so I will/have to implement most stuff myself.

**Comment by nils-wisiol** [comment]
Maybe you can rebase you branch onto this PR, then you could take advantage of whatever files are in here.

**Comment by nils-wisiol** [comment]
I am assuming these files are solely for documentation purpose and not used in the code. If I am mistaken, please clarify.

Please add these files to a separate repository, GitHub Gist or similar. They are non-essential to the project and serve documentation purposes only, hence we don't necessarily need them inside the repository. Furthermore, licensing by the BSI is unclear; and while it seems unlikely to be sued over this, it's better to not take chances.

**Comment by Armagetron** [comment]
It would actually be nice to have these files in the repo. The tests can then run against the provided sample files.

**Comment by nils-wisiol** [comment]
reopen if necessary

**Comment by Armagetron** [comment]
We want this for the eid types

**Pull request closed without merging**
